# Generated by Django 3.1 on 2021-07-20 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_auto_20210720_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='declared_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='declared at'),
        ),
    ]
