# Generated by Django 3.1 on 2021-06-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_category_incident_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='audios',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d'),
        ),
    ]
