# Generated by Django 3.1 on 2021-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_auto_20210725_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='proposition',
            field=models.JSONField(blank=True, default='{}', max_length=1055),
        ),
        migrations.AlterUniqueTogether(
            name='proposition',
            unique_together={('incident', 'person')},
        ),
    ]
