# Generated by Django 3.1 on 2021-06-27 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_auto_20210622_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='textual_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ConfirmOrInfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='date uplated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_api.incident')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='confirms',
            field=models.ManyToManyField(related_name='user_confirms', through='project_api.ConfirmOrInfirm', to=settings.AUTH_USER_MODEL),
        ),
    ]
