# Generated by Django 3.1 on 2021-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0005_auto_20210627_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorinfirm',
            name='decision',
            field=models.CharField(choices=[('DFT', 'RAS'), ('CNF', 'Confirm'), ('INF', 'Infirm')], default='DFT', max_length=3),
        ),
    ]
